import scrapy

class ArticleItem(scrapy.Item):
    title        = scrapy.Field()
    url          = scrapy.Field()
    content      = scrapy.Field()
    author       = scrapy.Field()
    published_at = scrapy.Field()
    source_name  = scrapy.Field()
    source_url   = scrapy.Field()
    source_type  = scrapy.Field()
    tags         = scrapy.Field()
    metadata     = scrapy.Field()

class RepositoryItem(scrapy.Item):
    github_id    = scrapy.Field()
    name         = scrapy.Field()
    full_name    = scrapy.Field()
    description  = scrapy.Field()
    url          = scrapy.Field()
    clone_url    = scrapy.Field()
    stars        = scrapy.Field()
    forks        = scrapy.Field()
    watchers     = scrapy.Field()
    open_issues  = scrapy.Field()
    language     = scrapy.Field()
    topics       = scrapy.Field()
    owner        = scrapy.Field()
    stars_today  = scrapy.Field()
    is_trending  = scrapy.Field()
    repo_created_at = scrapy.Field()
    metadata     = scrapy.Field()

class ResearchPaperItem(scrapy.Item):
    arxiv_id       = scrapy.Field()
    title          = scrapy.Field()
    abstract       = scrapy.Field()
    authors        = scrapy.Field()
    categories     = scrapy.Field()
    published_date = scrapy.Field()
    url            = scrapy.Field()
    pdf_url        = scrapy.Field()
    metadata       = scrapy.Field()

class VideoItem(scrapy.Item):
    youtube_id    = scrapy.Field()
    title         = scrapy.Field()
    description   = scrapy.Field()
    channel_name  = scrapy.Field()
    channel_id    = scrapy.Field()
    url           = scrapy.Field()
    thumbnail_url = scrapy.Field()
    duration_seconds = scrapy.Field()
    view_count    = scrapy.Field()
    like_count    = scrapy.Field()
    published_at  = scrapy.Field()
    topics        = scrapy.Field()
    metadata      = scrapy.Field()
